name: bytelyon

services:
  bro:
    image: "bytelyon/bro"
    build:
      context: ..
      dockerfile: infra/docker/bro.Dockerfile
      args:
        BRO_PORT: ${BRO_PORT:-8085}
    command:
      ["run", "app/main.py", "--host", "0.0.0.0", "--port", "${BRO_PORT}"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${BRO_PORT}:${BRO_PORT}"
    networks:
      - sail
    depends_on:
      - mux
  mux:
    image: "bytelyon/mux"
    build:
      context: ..
      dockerfile: infra/docker/mux.Dockerfile
      args:
        MUX_PORT: ${MUX_PORT:-3000}
    command: ["--log=$LOG_LEVEL"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${MUX_PORT}:${MUX_PORT}"
    networks:
      - sail
    depends_on:
      - web
  web:
    image: "sail-8.5/app"
    build:
      context: ..
      dockerfile: infra/docker/web.Dockerfile
      args:
        WWWGROUP: "${WWWGROUP:-1000}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT:-80}:80"
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    environment:
      WWWUSER: "${WWWUSER:-1000}"
      LARAVEL_SAIL: 1
      XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
      XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
      IGNITION_LOCAL_SITES_PATH: "${PWD:-apps/web}"
    volumes:
      - "../apps/web/.:/var/www/html"
    networks:
      - sail
    depends_on:
      - pgsql
      - redis
  pgsql:
    image: "postgres:18-alpine"
    ports:
      - "${FORWARD_DB_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "sail-pgsql:/var/lib/postgresql"
      - "../infra/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql"
    networks:
      - sail
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "${DB_DATABASE}",
          "-U",
          "${DB_USERNAME}",
        ]
      retries: 3
      timeout: 5s
  redis:
    image: "redis:alpine"
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - "sail-redis:/data"
    networks:
      - sail
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
networks:
  sail:
    driver: bridge
volumes:
  sail-pgsql:
    driver: local
  sail-redis:
    driver: local
