# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

POST http://127.0.0.1:8200/bot
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "type": "news",
  "query": "what is a plumbus?"
}

###
@query = situation in iran
@id = 1
@since = 2025-01-01T05:00:00Z

PUT 127.0.0.1:8085/news/{{id}}/query/{{query}}/since/{{since}}
Accept: application/json