# Test your FastAPI endpoints

GET http://127.0.0.1:8200/
Accept: application/json

###

POST http://127.0.0.1:8200/bot
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "type": "news",
  "query": "what is a plumbus?"
}

###
