[project]
name = "scripts"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "aioboto3>=15.5.0",
    "aiofiles>=25.1.0",
    "aiohttp>=3.14.3",
    "beautifulsoup4>=4.15.0",
    "boto3-stubs~=1.40.61",
    "colorlog>=6.12.0",
    "dataclasses-json>=0.6.7",
    "playwright>=1.62.0",
    "python-dotenv>=1.2.2",
    "pytz>=2026.3.post1",
    "seleniumbase>=4.51.10",
    "types-aioboto3>=15.5.0",
    "types-aiobotocore-s3>=3.9.0",
    "types-aiofiles>=25.1.0.20260518",
    "types-pytz>=2026.3.1.20260727",
]

